### ISSUE TITLE
Multiple bugs and features

### ISSUE THREAD

**Issue by szafranski-pawel** [cerber-os/SCZR#5]
1. Create new image generator
2. Create new data structure
3. Use shared memory in proper way.

More is coming 👍🏻

**Comment by szafranski-pawel** [comment]
1. We should be able to control "processing time" of image generator

**Comment by szafranski-pawel** [comment]
4. Check if our compression algorithm is working!

**Comment by cerber-os** [comment]
> 2. Create new data structure

Added with recent commit. From now packet structure looks as follow:
https://github.com/cerber-os/SCZR/blob/2cba7d8e564cb62cd7f41a3e00aa08f1299ea5a5/uapi/misc.h#L12-L19
Of course I'm open for any suggestions/fixes :smile: 

> 3. Use shared memory in proper way.

Shared memory queue mode was also added with recent PR

**Comment by szafranski-pawel** [comment]
> 1. Create new image generator

New image generator added.

> 4. Check if our compression algorithm is working!

Compression is working

**Comment by cerber-os** [comment]
> 1. We should be able to control "processing time" of image generator

Added with new image generator
